myapplication/config/routes.rb
Myapplication::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts
  resources :comments, only: [:create, :destroy]

  root  'static_pages#home'
  match '/topic',  to: 'posts#topic',            via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

myapplication/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 1000 }
  validates :post_id, presence: true
end

myapplication/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order('created_at DESC') }
  validates :title, presence: true, length: { maximum: 40 }
  validates :content, presence: true, length: { maximum: 1000 }
  validates :user_id, presence: true
end

myapplication/app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

myapplication/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

myapplication/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @users = User.all
    @comment = Comment.new(micropost_params)
    if @comment.save
      flash[:success] = "Comment done!"
      redirect_to(@comment.post)
    else
      redirect_to(@comment.post)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
 
    redirect_to(@comment.post)
  end

  private

    def micropost_params
      params.require(:comment).permit(:content,:post_id,:name)
    end
end

myapplication/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :signed_in_user

  def create
    @users = User.all
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def show
    @users = User.all
    @post = Post.find(params[:id])
    @user = @post.user
    # @comments = @posts.comments
    # @com = @posts.comments.build

    @comment = Comment.new( :post => @post )
  end

  def topic
    @users = User.all
    @postss = Post.where("topic = ?",params[:top])
  end

  def destroy
  end

  private

    def post_params
      params.require(:post).permit(:title,:content,:topic)
    end
end

myapplication/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @users=User.all
  end

  def create
    @users=User.all
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

myapplication/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @users=User.all
    @post = current_user.posts.build if signed_in?
  end

  def help
    @users=User.all
  end

  def contact
    @users=User.all
  end

  def about
    @users=User.all
  end
end

myapplication/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @users = User.all
    @posts = @user.posts(params[:page])
  end

  def new
    @user = User.new
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @users = User.all
  end

  def update
    @users = User.all
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

myapplication/app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "My Application's"
    if page_title.empty?
      base_title
    else
      "#{base_title} #{page_title}"
    end
  end
end

myapplication/app/helpers/comments_helper.rb
module CommentsHelper
end

myapplication/app/helpers/posts_helper.rb
module PostsHelper
end

myapplication/app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = cookies[:remember_token]
    @current_user ||= User.find_by(remember_token: User.encrypt(remember_token))
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

myapplication/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

myapplication/app/helpers/users_helper.rb
module UsersHelper
end

myapplication/app/views/layouts/_footer.html.erb
<!-- footer starts here -->	
<div id="footer-wrap">
	
	<div class="footer-left">
		<p class="align-left">			
		&copy; 2013 Training Project |
		<a href="#" title="Website">Official Website</a> by <a href="http://www.kreeti.com/">Kreeti Technologies</a>
       	</p>
	</div>
	
	<div class="footer-right">
		<p class="align-right">
		<%= link_to "Home",    root_path %> |
  		<%= link_to "About",    about_path %> |
   	        <%= link_to "Help",    help_path %>
		</p>
	</div>
	
</div>
<!-- footer ends here -->	

myapplication/app/views/layouts/_header.html.erb
<div id="header">			
	<h1 id="logo">Know<span class="gray">Hub</span></h1>	
	<h2 id="slogan">Rails Application in Development...</h2>		
	
	<!-- Menu Tabs -->
	<div id="menu">
		

myapplication/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

myapplication/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "style", media: "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <!-- wrap starts here -->
  <div id="wrap">
    <!-- content-wrap starts here -->
    <div id="content-wrap">	 
      <%= render 'layouts/header' %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <div class="clear"></div>
      <!-- content-wrap ends here -->
    </div>	
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

myapplication/app/views/posts/_comment.html.erb
<li>
  <%= comment.content %>
<br />

by <%= comment.name %>
<br />
<br />
<%= link_to 'Destroy Comment', comment,
    :confirm => 'Are you sure?',
    :method => :delete if signed_in? %>
</li>

myapplication/app/views/posts/_post.html.erb
<li>
  <%= link_to post.title, post %>
<br />
    <span class="grey">Posted <%= time_ago_in_words(post.created_at) %> ago.</span>
<br />
<br />
</li>

myapplication/app/views/posts/_sidebar.html.erb
<div id="sidebar" >
                        <h2>Search</h2>
			<div class="searchform">
				<form action="#">
					<p>
					<input name="search_query" class="textbox" type="text" />
  					<input name="search" class="button" value="Search" type="submit" />
					</p>
				</form>
			</div>
			<h2 class="clear">Topics Menu</h2>

			<ul class="sidemenu">
				<li><%= link_to "HTML & CSS",    topic_path(:top=>"HTML&CSS") %></li>
				<li><%= link_to "Ruby",    topic_path(:top=>"Ruby") %></li>
				<li><%= link_to "JavaScript",    topic_path(:top=>"JavaScript") %></li>
				<li><%= link_to "Git",    topic_path(:top=>"Git") %></li>
				<li><%= link_to "Rails",    topic_path(:top=>"Rails") %></li>
                                <li><%= link_to "Redis",    topic_path(:top=>"Redis") %></li>
                                <li><%= link_to "jQuery",    topic_path(:top=>"jQuery") %></li>
			</ul>

			<h2>Members</h2>
			    <ul class="sidemenu">
				<% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      
    </li>
  <% end %>
			    </ul>

			

			<h2>Wise Words</h2>
			<p>&quot;The happiest people are those who invested their time in others.
			The unhappiest people are those who wonder how the world is going to
			make them happy&quot;</p>

			<p class="align-right">- John Maxwell</p>

		</div>

myapplication/app/views/posts/show.html.erb
<% provide(:title, 'Profile: '+@post.title) %>
<ul>
		<li><%= link_to "Home",    root_path %></li>
		<li><%= link_to "About",    about_path %></li>
		<li><%= link_to "Contact",    contact_path %></li>
		<li><%= link_to "Help",    help_path %></li>
                <% if signed_in? %>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
		<% else %>
                <li><%= link_to "Sign in", signin_path %></li>
                <% end %>			
		</ul>		
	</div>			
</div>	


<div id="main">		
			<div class="box">
				
				<h1><span class="gray"><%= @post.title %></span></h1>
		<%= @post.content %><br /><br />
<% if signed_in? && current_user.admin==true && @user.admin==false %>
    | <%= link_to "delete", @post, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>		
Topic- <%= @post.topic %><br /><br />
Posted By- <%= @user.name %>
			</div>	
                       <div class="box">
<h1>Give <span class="gray">Comments</span></h1>



<%= form_for(@comment) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

    <%= f.hidden_field :post_id %>
    <%= f.hidden_field :name, :value => current_user.name %>
    <%= f.text_area :content, placeholder: "Compose new comment..." %>
    
    
<br />
<br />
<br />
  <%= f.submit "Comment" %>
<% end %>



                       </div>	
<div class="box">

<% if @post.comments.any? %>
      <h3>Comments (<%= @post.comments.count %>)</h3>
<ul class="sidemenu">
        <%= render :partial => 'comment', :collection => @post.comments %>
</ul>
    <% end %>

                       </div>		
		</div>
             <%= render 'sidebar' %>
	<br />

myapplication/app/views/posts/topic.html.erb
<% provide(:title, 'Post By Topic') %>
<ul>
		<li><%= link_to "Home",    root_path %></li>
		<li><%= link_to "About",    about_path %></li>
		<li><%= link_to "Contact",    contact_path %></li>
		<li><%= link_to "Help",    help_path %></li>
                <% if signed_in? %>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
		<% else %>
                <li><%= link_to "Sign in", signin_path %></li>
                <% end %>			
		</ul>		
	</div>			
</div>	


<div id="main">		
			<div class="box">
				
				<h1>Post <span class="gray">By Topic</span></h1>
				
<% if @postss.any? %>
      <h3>Posts (<%= @postss.count %>)</h3>
<ul class="sidemenu">
       <% @postss.each do |userr| %>
    <li>
      <%= link_to userr.title, userr %>
      <br />
    <span class="grey">Posted <%= time_ago_in_words(userr.created_at) %> ago.</span>
<br />
<br />
    </li>
  <% end %>
</ul>

    <% end %>

                       </div>		
		</div>
             <%= render 'sidebar' %>
	<br />

myapplication/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

myapplication/app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div>
<%= f.text_field :title, placeholder: "Give a title..." %>
<br />
<br />
    <%= f.text_area :content, placeholder: "Compose new post..." %>
<br />
<br />
<%= f.select :topic, options_for_select(%w[HTML&CSS Ruby JavaScript Git Rails Redis jQuery]) %>
  </div>
<br />
  <%= f.submit "Post" %>
<% end %>

myapplication/app/views/shared/_user_info.html.erb
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.posts.count, "post") %>
</span>

myapplication/app/views/static_pages/_sidebar.html.erb
<div id="sidebar" >
                        <h2>Search</h2>
			<div class="searchform">
				<form action="#">
					<p>
					<input name="search_query" class="textbox" type="text" />
  					<input name="search" class="button" value="Search" type="submit" />
					</p>
				</form>
			</div>
			<h2 class="clear">Topics Menu</h2>

			<ul class="sidemenu">
				<li><%= link_to "HTML & CSS",    topic_path(:top=>"HTML&CSS") %></li>
				<li><%= link_to "Ruby",    topic_path(:top=>"Ruby") %></li>
				<li><%= link_to "JavaScript",    topic_path(:top=>"JavaScript") %></li>
				<li><%= link_to "Git",    topic_path(:top=>"Git") %></li>
				<li><%= link_to "Rails",    topic_path(:top=>"Rails") %></li>
                                <li><%= link_to "Redis",    topic_path(:top=>"Redis") %></li>
                                <li><%= link_to "jQuery",    topic_path(:top=>"jQuery") %></li>
			</ul>

			<h2>Members</h2>
			    <ul class="sidemenu">
				<% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      
    </li>
  <% end %>
			    </ul>

			

			<h2>Wise Words</h2>
			<p>&quot;The happiest people are those who invested their time in others.
			The unhappiest people are those who wonder how the world is going to
			make them happy&quot;</p>

			<p class="align-right">- John Maxwell</p>

		</div>

myapplication/app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<ul>
		<li><%= link_to "Home",    root_path %></li>
		<li id="current"><%= link_to "About",    about_path %></li>
		<li><%= link_to "Contact",    contact_path %></li>
		<li><%= link_to "Help",    help_path %></li>
                <% if signed_in? %>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
		<% else %>
                <li><%= link_to "Sign in", signin_path %></li>
                <% end %>			
		</ul>		
	</div>			
</div>	
<div id="main">			
			<div class="box">
				
						<h1>About <span class="gray">Us</span></h1>

				<p>
				This site is dedicated to the On-going, but soon to end, pre-joining training session at Kreeti Technologies Pvt. Ltd.   
				</p>
				<p>
				Starting from HTML & CSS and almost at the end of it with jQuery.                
				</p>
				
			</div>
			
			<div class="box">
				<h1>The <span class="gray">Contributions</span></h1>	
						
				<blockquote>
                                <ul>					
					<li>Jayanta Mondal - HTML & CSS</li>
					<li>Suman Ghoshal - Linux</li>	
					<li>Anuroop Aich - Ruby</li>	
                                        <li>Ritika Agarwal - Git</li>
					<li>Abhidip Ray - JavaScript</li>	
                                        <li>Debalina Mukherjee - Rails</li>
					<li>Prosenjit Saha - Rails</li>	
                                        <li>Ramyani Ghosh - Redis</li>
					<li>Priya Rani - jQuery</li>								
				</ul>
                                </blockquote>
						
				
				<br />	
			
			</div>	
							
		</div>
             <%= render 'sidebar' %>
	<br />

myapplication/app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<ul>
		<li><%= link_to "Home",    root_path %></li>
		<li><%= link_to "About",    about_path %></li>
		<li id="current"><%= link_to "Contact",    contact_path %></li>
		<li><%= link_to "Help",    help_path %></li>
                <% if signed_in? %>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
		<% else %>
                <li><%= link_to "Sign in", signin_path %></li>
                <% end %>			
		</ul>		
	</div>			
</div>	
<div id="main">		
			<div class="box">
				
				<h1>Contact <span class="gray">Us</span></h1>
				
                <p>Feel free to contact us any time.
                </p>
		<form action="#">		
					<p>				
					<label>Name</label>
					<input name="dname" value="Your Name" type="text" size="30" />
					<label>Email</label>
					<input name="demail" value="Your Email" type="text" size="30" />
					<label>Your Comments</label>
					<textarea rows="5" cols="5"></textarea>
					<br />	
					<input class="button" type="submit" />		
					</p>		
				</form>		
				
			</div>			
		</div>
             <%= render 'sidebar' %>
	<br />

myapplication/app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<ul>
		<li><%= link_to "Home",    root_path %></li>
		<li><%= link_to "About",    about_path %></li>
		<li><%= link_to "Contact",    contact_path %></li>
		<li id="current"><%= link_to "Help",    help_path %></li>
                <% if signed_in? %>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
		<% else %>
                <li><%= link_to "Sign in", signin_path %></li>
                <% end %>			
		</ul>		
	</div>			
</div>	
<div id="main">			
			<div class="box">
				
				<h1>Help <span class="gray">Section</span></h1>
				
                <p>If you dont know what this site is, you can always contact us and ask or you can read a lot more about us.
                </p>
                <p>More Help features coming soon...!!!
                </p>
				
				<p class="comments">
					<%= link_to "Contact",    contact_path %> |
					<%= link_to "About",    about_path %> | 
					Jul 30, 2013
				</p>
				
			</div>			
		</div>
             <%= render 'sidebar' %>
	<br />

myapplication/app/views/static_pages/home.html.erb
<% provide(:title, 'Home Page') %>
<% if signed_in? %>
<ul>
		<li id="current"><%= link_to "Home",    root_path %></li>
		<li><%= link_to "About",    about_path %></li>
		<li><%= link_to "Contact",    contact_path %></li>
		<li><%= link_to "Help",    help_path %></li>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>	
		</ul>		
	</div>			
</div>		
<div id="main">

<div class="box">

<section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/post_form' %>
      </section>

</div>

</div>
<%= render 'sidebar' %>
	<br />
<% else %>
<ul>
		<li id="current"><%= link_to "Home",    root_path %></li>
		<li><%= link_to "About",    about_path %></li>
		<li><%= link_to "Contact",    contact_path %></li>
		<li><%= link_to "Help",    help_path %></li>
                <li><%= link_to "Sign In",    signin_path %></li>	
		</ul>		
	</div>			
</div>
<div id="main">
				
			<div class="box">
				
				<h1>Demo <span class="gray">Application</span></h1>
				
                <p><%= link_to "Sign up now!", signup_path%><br /><br />This Rails Application <strong>asifkhan</strong> is a free, W3C-compliant, CSS-based website
                by <a href="http://www.asifkhan.com/">Asif Khan</a>.
                It is just a demo application that is created to practice Rails more and program accordingly.
                This site is just for demonstration purpose and has no existence in the real world whatsoever.
                </p>
				
				<p class="comments">
                                        <%= link_to "- Asif Khan",    root_path %>
					Jul 30, 2013
				</p>
				
			</div>
			
			<a name="SampleTags"></a>
			<div class="box">
				<h1>Website <span class="gray">Features</span></h1>
				

                                <h3>Demo Text and Photo</h3>
				<p><%= link_to image_tag("firefox-gray.jpg", alt: "firefox-gray", width:"100", height:"121", class:"float-left"), 'http://rubyonrails.org/' %>
				Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. 
				Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu 
				posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum, dui pede condimentum 
				odio, ac blandit ante orci ut diam. Cras fringilla magna. Phasellus suscipit, leo a pharetra 
				condimentum, lorem tellus eleifend magna, eget fringilla velit magna id neque. Curabitur vel urna. 
				In tristique orci porttitor ipsum. Aliquam ornare diam iaculis nibh. Proin luctus, velit pulvinar 
				ullamcorper nonummy, mauris enim eleifend urna, congue egestas elit lectus eu est. 				
				</p>

                                <h3>Language</h3>
				<p>Ruby 2.0.0				
				</p>	
                                <h3>Framework</h3>
				<p>Rails 4.0.0				
				</p>							
				<h3>Database</h3>
				<p>SQLite3			
				</p>	
                                
				<br />	
			
			</div>	
							
		</div>
             <%= render 'sidebar' %>
	<br />
<% end %>

myapplication/app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<ul>
		<li><%= link_to "Home",    root_path %></li>
		<li><%= link_to "About",    about_path %></li>
		<li><%= link_to "Contact",    contact_path %></li>
		<li><%= link_to "Help",    help_path %></li>
                <% if signed_in? %>
                <li><%= link_to "Profile", current_user %></li>
                <li id="current"><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
		<% else %>
                <li><%= link_to "Sign in", signin_path %></li>
                <% end %>			
		</ul>		
	</div>			
</div>	
<div id="main">		
			<div class="box">
				
				<h1>Sign <span class="gray">Up</span></h1>
				
                <p>FIll in the form below to change settings
                </p>		
		<%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>
<br />
<br />
      <%= f.submit "Save changes" %>
    <% end %>		
			</div>			
		</div>
             <%= render 'static_pages/sidebar' %>
	<br />

myapplication/app/views/users/index.html.erb
				
			<% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>			

myapplication/app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<ul>
		<li><%= link_to "Home",    root_path %></li>
		<li><%= link_to "About",    about_path %></li>
		<li><%= link_to "Contact",    contact_path %></li>
		<li><%= link_to "Help",    help_path %></li>
                <% if signed_in? %>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
		<% else %>
                <li><%= link_to "Sign in", signin_path %></li>
                <% end %>			
		</ul>		
	</div>			
</div>	
<div id="main">		
			<div class="box">
				
				<h1>Sign <span class="gray">Up</span></h1>
				
                <p>FIll in the form below to sign up
                </p>		
		<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
<br />
<br />
      <%= f.submit "Create my account" %>
    <% end %>		
			</div>			
		</div>
             <%= render 'static_pages/sidebar' %>
	<br />

myapplication/app/views/users/show.html.erb
<% provide(:title, 'Profile: '+@user.name) %>
<ul>
		<li><%= link_to "Home",    root_path %></li>
		<li><%= link_to "About",    about_path %></li>
		<li><%= link_to "Contact",    contact_path %></li>
		<li><%= link_to "Help",    help_path %></li>
                <% if signed_in? %>
                <li id="current"><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
		<% else %>
                <li><%= link_to "Sign in", signin_path %></li>
                <% end %>			
		</ul>		
	</div>			
</div>	
<div id="main">		
			<div class="box">
				
				<h1>Your <span class="gray">Profile</span></h1>
				
		<%= @user.name %>
<% if signed_in? && current_user.admin==true && @user.admin==false %>
    | <%= link_to "delete", @user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>		
			</div>	
                       <div class="box">

<% if @user.posts.any? %>
      <h3>Posts (<%= @user.posts.count %>)</h3>
<ul class="sidemenu">
        <%= render @posts %>
</ul>

    <% end %>

                       </div>		
		</div>
             <%= render 'static_pages/sidebar' %>
	<br />